# Generated by Django 5.1.2 on 2025-08-05 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('artist', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('format', models.CharField(choices=[('DD', 'Digital Download'), ('CD', 'CD'), ('VL', 'Vinyl')], max_length=2)),
                ('release_date', models.DateField()),
                ('cover_image', models.ImageField(blank=True, default='default_cover.jpg', null=True, upload_to='album_covers/')),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('running_time', models.PositiveIntegerField(help_text='Length of the song in seconds (≥ 10)')),
            ],
        ),
        migrations.CreateModel(
            name='MusicManagerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('permission', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('artist', 'Artist')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumTracklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.song')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('album', 'song')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(through='catalogue.AlbumTracklistItem', to='catalogue.song'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('title', 'artist', 'format'), name='unique_album_per_artist_format'),
        ),
    ]
