# Generated by Django 5.1.2 on 2025-08-09 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_remove_song_duration_song_running_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='running_time',
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(default='10', help_text='Duration in seconds (minimum 10)', validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
