# Generated by Django 5.1.2 on 2025-08-08 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='running_time',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='Unknown Artist', max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(default='10', help_text='Duration in seconds (minimum 10)', validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
