# Generated by Django 5.1.2 on 2025-08-09 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_remove_song_running_time_song_artist_song_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AddField(
            model_name='song',
            name='running_time',
            field=models.PositiveIntegerField(default='10', help_text='running_time in seconds (minimum 10)', validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
