# Generated by Django 5.1.2 on 2025-08-10 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_remove_song_running_time_song_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.PositiveIntegerField(default=10, help_text='Length in seconds (minimum 10)', validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
